UPC.TP2.WEB/Controllers/GenerarServiciosPlanController.cs
using Newtonsoft.Json.Linq;
using System;
using System.Collections.Generic;
using System.Data;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using UPC.TP2.WEB.Models;
using UPC.TP2.WEB.ViewModels;
using UPC.TP2.WEB.Utils;

namespace UPC.TP2.WEB.PlanSalud.Controllers
{
    public class GenerarServiciosPlanController : Controller
    {
        private BDCLINICAEntities db = new BDCLINICAEntities();
        // GET: /GenerarServiciosPlan/

        public ActionResult Index()
        {
            return View();
        }

        public ActionResult Generar()
        {
            //Validation dates

            HttpRequestBase request = Request.Form.AllKeys.Length == 0 ? (HttpRequestBase)TempData["request"] : Request;
            ViewBag.Message = TempData["Message"];

            string fi = request != null ? request["fecha_inicio"] ?? String.Empty : String.Empty;
            string ff = request != null ? request["fecha_fin"] ?? String.Empty : String.Empty;

            ViewBag.FechaInicio = fi;
            ViewBag.FechaFin = ff;

            if (fi == String.Empty || ff == String.Empty)
            {
                return View("Index");
            }
            else
            {
                try
                {

                    DateTime dtfi = DateTime.Parse(fi);
                    DateTime dtff = DateTime.Parse(ff);

                    long dif = dtff.CompareTo(dtfi);

                    if (dif < 0)
                    {
                        ViewBag.Message = "La fecha final no debe ser menor que la inicial";
                        return View("Index");
                    }

                }
                catch (FormatException)
                {
                    ViewBag.Message = "Verifique que las fechas sean correctas";
                    return View("Index");
                }
            }

            //-- BEGIN: Full logic 

            DateTime FechaInicio = DateTime.Parse(fi);
            DateTime FechaFin = DateTime.Parse(ff);

            List<T_PROGRAMACION_MEDICA> ret_serv = db.T_PROGRAMACION_MEDICA
                .Where(x => x.fecha >= FechaInicio && x.fecha <= FechaFin)
                .ToList();

            List<T_PROGRAMACION_MEDICA> asi_plan = db.T_PROGRAMACION_MEDICA
                .Where(x => x.fecha >= FechaInicio && x.fecha <= FechaFin)
                .ToList();

            List<T_ESPECIALIDAD_MEDICA> esp = db.T_ESPECIALIDAD_MEDICA.ToList();
            List<T_ESPECIALIDAD_SERVICIO> esp_serv = db.T_ESPECIALIDAD_SERVICIO.ToList();
            List<T_PLAN_DE_SALUD> pla_salu = db.T_PLAN_DE_SALUD.ToList();
            List<T_PERSONA_PLANSALUD> per_pla_salu = db.T_PERSONA_PLANSALUD.ToList();

            T_CONFIGURACION config_asignar = db.T_CONFIGURACION.Where(x => x.indicador == "asignar_servicio").FirstOrDefault();
            T_CONFIGURACION config_retirar = db.T_CONFIGURACION.Where(x => x.indicador == "retirar_servicio").FirstOrDefault();

            //## TABLA DE RETIRO
            object obj_ret_serv = from pla_ser in db.T_PLAN_SERVICIO.Where(x => x.estado == "1").ToList()
                                  join pla in db.T_PLAN_DE_SALUD on pla_ser.id_plan_salud equals pla.id_plan_salud
                                  join per_pla in db.T_PERSONA_PLANSALUD on pla.id_plan_salud equals per_pla.id_plan_salud into gj_per_pla
                                  from per_pla in gj_per_pla.DefaultIfEmpty(new T_PERSONA_PLANSALUD())
                                  join per in db.T_PERSONA on per_pla.codPersona equals per.codPersona
                                  join pro in db.T_PROGRAMACION_MEDICA.Where(x=> x.estado == "1" && x.fecha >= FechaInicio && x.fecha <= FechaFin) on //Use direct table in replace of "ret_ser"
                                    new { pla_ser.idEspecialidad, pla_ser.id_servicio } equals
                                    new { pro.idEspecialidad, pro.id_servicio }  into gj_pro
                                  from pro in gj_pro.DefaultIfEmpty()
                                  where pro == null || ( pro != null && pro.fecha >= per_pla.fecha_inicio && pro.fecha <= per_pla.fecha_fin)
                                  group 
                                    new { pla_ser, pla, per_pla } 
                                    by new { pla_ser.id_plan_salud, pla_ser.idEspecialidad, pla_ser.id_servicio } into gbx
                                  select new
                                  {
                                      id_plan_salud = gbx.Key.id_plan_salud,
                                      id_especialidad = gbx.Key.idEspecialidad,
                                      id_servicio = gbx.Key.id_servicio,
                                      nombre_plan_salud = gbx.ToList().FirstOrDefault().pla_ser.T_PLAN_DE_SALUD.nombre_plan,
                                      nombre_especialidad = gbx.ToList().FirstOrDefault().pla_ser.T_ESPECIALIDAD_SERVICIO.T_ESPECIALIDAD_MEDICA.nomEspecialidad,
                                      nombre_servicio = gbx.ToList().FirstOrDefault().pla_ser.T_ESPECIALIDAD_SERVICIO.T_SERVICIO_SALUD.nombre_servicio,
                                      cantidad = gbx.Count(c => c != null),
                                      color = (gbx.Count(c => c != null) <= Int32.Parse(config_retirar.valor_maximo) && gbx.Count(c => c != null) >= Int32.Parse(config_retirar.valor_minimo)) ? "orange" : ""
                                  };


            //## TABLA DE ASIGNACION
            object obj_asi_plan = from pro in asi_plan
                                  join per in db.T_PERSONA on pro.codPersona equals per.codPersona
                                  join pla_ser in db.T_PLAN_SERVICIO on 
                                    new { pro.idEspecialidad, pro.id_servicio } equals
                                    new { pla_ser.idEspecialidad, pla_ser.id_servicio } into gj_ppp                                
                                  from pla_ser in gj_ppp.DefaultIfEmpty() //This is LEFT JOIN
                                  join per_pla in db.T_PERSONA_PLANSALUD on per.codPersona equals per_pla.codPersona into gj_per_pla
                                  from per_pla in gj_per_pla.DefaultIfEmpty() //This is LEFT JOIN                                 
                                  where per_pla == null ||
                                        ((pla_ser != null && pla_ser.estado == "0") &&
                                        (pro.fecha < per_pla.fecha_inicio && pro.fecha > per_pla.fecha_fin))
                                  group
                                    new { pro, per, per_pla, pla_ser }
                                    by new { pro.idEspecialidad, pro.id_servicio } into gb
                                  select new
                                  {
                                      id_especialidad = gb.Key.idEspecialidad,
                                      id_servicio = gb.Key.id_servicio,
                                      nombre_especialidad = gb.ToList().FirstOrDefault().pro.T_ESPECIALIDAD_SERVICIO.T_ESPECIALIDAD_MEDICA.nomEspecialidad,
                                      nombre_servicio = gb.ToList().FirstOrDefault().pro.T_ESPECIALIDAD_SERVICIO.T_SERVICIO_SALUD.nombre_servicio,
                                      cantidad = gb.Count(),
                                      color = (gb.Count() <= Int32.Parse(config_retirar.valor_maximo) && gb.Count() >= Int32.Parse(config_retirar.valor_minimo)) ? "orange" : ""
                                  };


            GenerateServiceModel GSM = new GenerateServiceModel()
            {
                LIST_RETIRO_SERVICIO = ret_serv,
                LIST_ASIGNA_PLAN = asi_plan,
                LIST_PLAN_DE_SALUD = pla_salu,
                T_CONFIGURACION_ASIGNAR = config_asignar,
                T_CONFIGURACION_RETIRAR = config_retirar,
                JSON_LIST_RETIRO_SERVICIO = JArray.FromObject(obj_ret_serv, Util.jsonNoLoop()),
                JSON_LIST_ASIGNA_PLAN = JArray.FromObject(obj_asi_plan, Util.jsonNoLoop())
            };

            //-- END: Full logic

            return View("GenerateServices", GSM);
        }

        [HttpPost]
        public ActionResult GenerarAction()
        {
            
            TempData["request"] = Request;
            string accion = Request["accion"] ?? "";

            if(accion == "retirar")
            {
                List<string> keys_retirar = Request.Form.AllKeys.Select(x => x).Where(x => x.StartsWith("checkbox_retirar_")).ToList();
                foreach (string item in keys_retirar)
                {
                    string[] splits = item.Split('_');
                    int key_plan = Int32.Parse(splits[2]);
                    int key_espe = Int32.Parse(splits[3]);
                    int key_serv = Int32.Parse(splits[4]);

                    List<T_PLAN_SERVICIO> list_ps_m = null; //PLAN SERVICIOS MODIFICAR
                    T_PLAN_SERVICIO ps_n = null; //PLAN SERVICIO NUEVO

                    try
                    {
                        list_ps_m = db.T_PLAN_SERVICIO.Where(x => x.id_plan_salud == key_plan && x.idEspecialidad == key_espe && x.id_servicio == key_serv).ToList();

                        foreach (var ps_m in list_ps_m)
                        {
                            //MODIFY VALUES FOR RECORD
                            ps_m.estado = "0";
                            ps_m.fecha_fin = DateTime.Now;
                            db.Entry(ps_m).State = EntityState.Modified;

                            db.SaveChanges(); //MODIFY RECORD
                        }

                    }
                    catch (Exception e)
                    {

                    }                   

                    if (list_ps_m != null)
                    {
                        DateTime? fecha_fin = db.T_PLAN_DE_SALUD.Find(key_plan).fecha_fin;
                       

UPC.TP2.WEB/Views/GenerarServiciosPlan/ChartServicios.cshtml
@{
    ViewBag.Title = "ChartServicios";
}

<h2>ChartServicios</h2>

<div>
    <img src="@Url.Action("ChartServicios")" alt="chart" />
</div>

UPC.TP2.WEB/Views/GenerarServiciosPlan/GenerateServices.cshtml
@using Newtonsoft.Json.Linq
@model UPC.TP2.WEB.ViewModels.GenerateServiceModel

@{
    ViewBag.Title = "GenerateServices";
}

<script type="text/javascript">
</script>

<h2>Generar Servicios</h2>
<br />
<h3>@ViewBag.Message</h3>

@{Html.BeginForm("GenerarAction", "GenerarServiciosPlan", FormMethod.Post, new { @class = "some_class", @id = "form_generar_accion" });}

<input type="hidden" id="fecha_inicio" name="fecha_inicio" value="@ViewBag.FechaInicio" />
<input type="hidden" id="fecha_fin" name="fecha_fin" value="@ViewBag.FechaFin" />
<input type="hidden" id="accion" name="accion" value="X"/>

<div class="container-fluid">
    <div class="row">
        <div class="span6">
            <div class="page-header" style="margin: 0px 0;">
                <h1><small>Gr&aacute;fico</small></h1>
            </div>
            <!--CHART-->
        </div>
        <div class="span6">
            <div class="page-header" style="margin: 0px 0;">
                <h1><small>Gr&aacute;fico</small></h1>
            </div>
            <!--CHART-->
        </div>
    </div>

    <div class="row">
        <div class="span6">
            <div class="page-header" style="margin: 0px 0;">
                <h1><small>Retirar servicio</small></h1>
            </div>
            <table id="table_retirar" class="display nowrap dataTable dtr-inline collapsed">
                <thead>
                    <tr>
                        <th>Seleccionar</th>
                        <th>Plan salud</th>
                        <th>Especialidad</th>
                        <th>Servicio</th>
                        <th>Cantidad</th>
                    </tr>
                </thead>
                <tbody>
                    @{  }
                    @foreach (JObject item in Model.JSON_LIST_RETIRO_SERVICIO)
                    {
                        var keys = item["id_plan_salud"] + "_" + item["id_especialidad"] + "_" + item["id_servicio"];
                        <tr style="background-color: @item["color"]">
                            <td><input type="checkbox" name="checkbox_retirar_@keys"/></td>
                            <td>@item["nombre_plan_salud"]</td>
                            <td>@item["nombre_especialidad"]</td>
                            <td>@item["nombre_servicio"]</td>
                            <td>@item["cantidad"]</td>
                        </tr>
                    }
                </tbody>
                <tfoot>
                    <tr>
                        <th colspan="4"><input id="submit_retirar" type="button" value="Retirar servicio" /></th>
                    </tr>
                </tfoot>
            </table>
        </div>
        <div class="span6">
            <div class="page-header" style="margin: 0px 0;">
                <h1><small>Asignar servicio</small></h1>
            </div>
            <table id="table_asignar" class="display nowrap dataTable dtr-inline collapsed">
                <thead>
                    <tr>
                        <th>Selecione</th>
                        <th>Especialidad</th>
                        <th>Servicio</th>
                        <th>Cantidad</th>
                        <th>Plan de salud</th>
                    </tr>
                </thead>
                <tbody>
                    @{  }
                    @foreach (JObject item in Model.JSON_LIST_ASIGNA_PLAN)
                    {
                        var keys = item["id_especialidad"] + "_" + item["id_servicio"];
                        <tr style="background-color: @item["color"]">
                            <td><input type="checkbox" name="checkbox_asignar_@keys"/></td>                           
                            <td>@item["nombre_especialidad"]</td>
                            <td>@item["nombre_servicio"]</td>
                            <td>@item["cantidad"]</td>
                            <td>
                                <select id="select_plan_salud_@keys" name="select_plan_salud_@keys">
                                    @foreach (var p in Model.LIST_PLAN_DE_SALUD)
                                    {
                                        <option value="@p.id_plan_salud">@p.nombre_plan</option>
                                    }
                                </select>
                            </td>
                        </tr>
                    }
                </tbody>
                <tfoot>
                    <tr>
                        <th colspan="4"><input id="submit_asignar" type="button" value="Asignar servicio" /></th>
                    </tr>
                </tfoot>
            </table>
        </div>
    </div>
</div>


@{Html.EndForm();}

UPC.TP2.WEB/Views/GenerarServiciosPlan/Index.cshtml
@{
    ViewBag.Title = "Index";
}

<table class="table">
    <tr>
        <td>
            <div class="header">
                <h3 class="title">Generar Servicios de Planes de Salud</h3>
            </div>
        </td>
    </tr>
    <tr>
        <td>
            <div class="content">
                @{Html.BeginForm("Generar", "GenerarServiciosPlan", FormMethod.Post, new { @class = "some_class", @id = "form_generar_servicio_salud" });}
                <div class="col-md-6">
                    <div class="form-group">
                        <label>Fecha inicio</label>
                        <input id="fecha_inicio" name="fecha_inicio" type="date" class="form-control datepicker" placeholder="Fecha inicio" value="01/01/2015">
                    </div>
                </div>
            </div>
        </td>
        <td>
            <div class="col-md-6">
                <div class="form-group">
                    <label>Fecha Fin</label>
                    <input id="fecha_fin" name="fecha_fin" type="date" class="form-control datepicker" placeholder="Fecha fin" value="30/12/2017">
                </div>
            </div>
        </td>
        </tr>
    <tr>
        <td>
            <div class="col-md-6">
                <div class="form-group">
                    <input id="submit_generar_servicio_salud" name="submit_generar_servicio_salud" value="Generar Servicio de Salud" type="submit" class="btn btn-info btn-fill pull-left" />
                </div>
            </div>
        </td>
    </tr>
    <tr>
        <td>
            @{Html.EndForm();}
        </td>
            <br />

            @ViewBag.Message

            <div class="clearfix"></div>

        </td>
    </tr>
</table>

UPC.TP2.WEB/Views/GenerarServiciosPlan/Index_OLD.cshtml
@{
    ViewBag.Title = "Index";
}

<div class="row">
    <div class="col-md-8">
            <div class="header">
                <h4 class="title">Generar Servicios de Planes de Salud</h4>
            </div>
            <div class="content">
                <from>
                    <div class="row">
                        <div class="col-md-6">
                            <div class="form-group">
                                <label>Seleccionar fecha: Desde</label>
                                <input id="fecha_inicio" name="fecha_inicio" type="text" class="form-control datepicker" placeholder="Fecha inicio" value="01/01/2017">
                            </div>
                        </div>
                        <div class="col-md-6">
                            <div class="form-group">
                                <label>Hasta</label>
                                <input id="fecha_fin" name="fecha_fin" type="text" class="form-control datepicker" placeholder="Fecha fin" value="30/01/2017">
                            </div>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-md-6">
                            <div class="form-group">
                                @Html.ActionLink("Generar", "Resultado", "PlanServicio")
                                <input name="submit_informe_tipo" value="Generar Informe" type="submit" class="btn btn-info btn-fill pull-left" />
                            </div>
                        </div>
                    </div>
                </from>

                <div class="clearfix"></div>
               
            </div>
    </div>

</div>